package com.dannybierek.tools.hmc.model

enum class FileType(descriptor: String) {
    AIBB("BehaviorTreeEntityBlueprint"),
    AIBX("BehaviorTreeEntityType"),
    AIBZ("CompiledBehaviorTreeResource"),
    AIRG("ReasoningGridResource"),
    ALOC("Physics"),
    ASEB("AspectEntityBlueprint"),
    ASET("AspectEntityType"),
    ASVA("AnimationSetVariation"),
    ATMD("AnimationTakeMetaData"),
    BLOB("ResourceBlob"),
    BMSK("BoneMask"),
    BORG("AnimationBoneData"),
    BOXC("RenderBoxReflectionCache"),
    CBLU("CppEntityBlueprint"),
    CLNG("DialogCascadingLanguageDependencies"),
    CPPT("CppEntityType"),
    CRMD("CrowdMapDataResource"),
    DITL("DialogSoundTemplateList"),
    DLGE("DialogEvent"),
    DSWB("SAudioSwitchBlueprintData"),
    ECPB("ExtendedCppEntityBlueprint"),
    ECPT("ExtendedCppEntityType"),
    ENUM("EnumType"),
    ERES("EntityResource"),
    FXAC("FaceFX Actor"),
    FXAS("FaceFX AnimSet"),
    GFXF("ScaleformGFx"),
    GFXI("ScaleformGFx Images"),
    GFXV("ScaleformGfx Video"),
    GIDX("GlobalResourceIndex"),
    HIKC("HIKCharacter"),
    IMAP("IDMap"),
    JSON("JsonResource"),
    LINE("TextLine"),
    LOCR("LocalizationResource"),
    MATB("RenderMaterialEntityBlueprint"),
    MATE("RenderMaterialEffect"),
    MATI("RenderMaterialInstance"),
    MATT("RenderMaterialEntityType"),
    MJBA("MorphemeJointBoneAnimationData"),
    MRTN("MorphemeRuntimeNetwork"),
    MRTR("MorphemeRuntimeRig"),
    NAVP("NavpowerNavmesh"),
    ORES("OnlineResource"),
    PREL("Preload"),
    PRIM("RenderPrimitive"),
    REPO("Repository"),
    RTLV("RuntimeLocalizedVideo"),
    SCDA("ScatterData"),
    SDEF("SoundDefinitions"),
    SLMX("SelectMatrix"),
    TBLU("TemplateEntityBlueprint"),
    TELI("TextList"),
    TEMP("TemplateEntity"),
    TEXD("RenderTextureData"),
    TEXT("RenderTexture"),
    UICB("UIControl Blueprint"),
    UICT("UIControl Template"),
    VIDB("VideoDatabaseResource"),
    VTXD("VertexData"),
    WBNK("WwiseBank"),
    WSGB("AudioStateBlueprint"),
    WSGT("AudioStateType"),
    WSWB("AudioSwitchBlueprint"),
    WSWT("AudioSwitchType"),
    WWEM("Wwise Encoded Media"),
    WWES("Wwise Encoded Media (HITMAN 3 specific, contains dialogue)"),
    WWEV("Wwise Event"),
    YSHP("PhysicsSystem")
}